services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TIDAL_QUALITY=LOSSLESS
    volumes:
      - ./backend:/app
      - ./downloads:/app/downloads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - frontend_pnpm_store:/app/node_modules

volumes:
  downloads:
  frontend_pnpm_store:
